# Generated by Django 5.2 on 2025-04-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exercise', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
