# Generated by Django 5.2 on 2025-04-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintore_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininglog',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='traininglog',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='traininglog',
            name='weight',
        ),
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('training_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='kintore_app.traininglog')),
            ],
        ),
    ]
